name: "lftp sync"
description: "A simple action that allows you to use LFTP securely in a GitHub workflow"
branding:
  icon: "upload-cloud"
  color: "orange"
inputs:
  ftp_host:
    required: true
    type: string
  ftp_protocol:
    required: false
    default: "sftp"
    type: string
  ftp_user:
    required: false
    default: "anonymous"
    type: string
  ftp_pass:
    required: false
    type: string
  ftp_port:
    required: false
    default: "22"
    type: string
  ssh_private_key:
    required: false
    type: string
  ftp_host_fingerprint:
    required: false
    type: string
  disable_strict_host_key_checking:
    required: false
    type: string
  force_ssl:
    required: false
    default: "false"
    type: string
  ssl_verify_cert:
    required: false
    default: "false"
    type: string
  commands:
    required: false
    type: string
  debug:
    required: false
    default: "false"
    type: string
runs:
  using: "docker"
  image: "Dockerfile"
