name: "lftp sync"
description: "A simple action that allows you to use LFTP securely in a GitHub workflow"
branding:
  icon: "upload-cloud"
  color: "orange"
inputs:
  ftp_host:
    required: true
    description: "The hostname to connect to"
  ftp_protocol:
    required: false
    default: "sftp"
    description: "What protocol to use; sftp, ftp"
  ftp_user:
    required: false
    default: "anonymous"
    description: "FTP username"
  ftp_pass:
    required: false
    description: "FTP password if required"
  ftp_port:
    required: false
    default: "22"
    description: "FTP port"
  ssh_private_key:
    required: false
    description: "SSH private key which will be used when connecting over SFTP"
  ftp_host_fingerprint:
    required: false
    description: "The SSH host fingerprint to verify when connecting"
  disable_strict_host_key_checking:
    required: false
    default: "false"
    description: "Disable StrictHostKeyChecking (not recommended)"
  force_ssl:
    required: false
    default: "true"
    description: "if true, refuse to send password in clear when server does not support SSL"
  ssl_verify_cert:
    required: false
    default: "false"
    description: "when true, lftp checks if the host name used to connect to the server corresponds to the hostname in its certificate"
  commands:
    required: false
    description: "All commands for lftp seperated with ;"
  debug:
    required: false
    default: "false"
    description: "Turn on debug mode"
runs:
  using: "docker"
  image: "docker://ghcr.io/haukurh/lftp-action-image:1.0.0"
